--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/larin/wallpaper/wallpaper.png"

-- Special
background="#1b1b13"
foreground="#d6d4d9"
cursor="#d6d4d9"

-- Colors
color0="#1b1b13"
color1="#7EA130"
color2="#76884B"
color3="#8FA44A"
color4="#61718F"
color5="#8C839E"
color6="#9F9D9D"
color7="#d6d4d9"
color8="#959497"
color9="#7EA130"
color10="#76884B"
color11="#8FA44A"
color12="#61718F"
color13="#8C839E"
color14="#9F9D9D"
color15="#d6d4d9"
