# Shell variables
# Generated by 'wal'
wallpaper='/home/larin/wallpaper/wallpaper.png'

# Special
background='#1b1b13'
foreground='#d6d4d9'
cursor='#d6d4d9'

# Colors
color0='#1b1b13'
color1='#7EA130'
color2='#76884B'
color3='#8FA44A'
color4='#61718F'
color5='#8C839E'
color6='#9F9D9D'
color7='#d6d4d9'
color8='#959497'
color9='#7EA130'
color10='#76884B'
color11='#8FA44A'
color12='#61718F'
color13='#8C839E'
color14='#9F9D9D'
color15='#d6d4d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
